### ISSUE TITLE
Addition of Modify Entity Value

### ISSUE THREAD

**Issue by kpjorgen** [BCLibCoop/nnels-drupal-modules-cals_importer#5]
Hi Dave,

We are looking to add the following fields to the “modify entity value” operation (on the “parse” page: https://nnels.ca/admin/content/cals/records-sets/let-dogs-be-dogs). This would allow the addition of data into the field in bulk, at the point of parsing, instead of manually to each record.

Ideally, we would be able to: 

A. add the “Accrual method” field to the “modify entity value” operation. There are only 2 possible values for this field: “purchased” and “publisher”

B. add the “date created” field to the “modify entity value". This should always be the YYYY that we publish the file. If it can be populated automatically into the records, even better than me/us having to do it!

NOTE: Farrah and Dave are discussing this in email.

Thanks,
Kris

**Comment by gitschatz** [comment]
Farrah and I happened across this and figured out Item B in 5 min during our meeting today. 

Item A turned out was not needed as it's unlikely to be shared among all file resources for nodes in a record set.
