### ISSUE TITLE
Multiple Publishers within Record

### ISSUE THREAD

**Issue by kpjorgen** [BCLibCoop/nnels-drupal-modules-cals_importer#6]
Hi Dave,

Sometimes a record will have a file with a different publisher, i.e. the DAISY will be published by NNELS, the MP3 by another entity. What’s the best way to show that? 

For example, this MP3 file here should display a different publisher than the other files:  https://nnels.ca/items/unsettling-canada-national-wake-call 

Currently we can add another publisher to the main record, but this doesn’t tell who produced which file format (a problem for the exporter).

Thanks,
Kris

**Comment by wissensschatz** [comment]
Defunct (per-file publisher field has been achieved).
