### ISSUE TITLE
Parse / Test single collection item export functionality

### ISSUE THREAD

**Issue by gitschatz** [BCLibCoop/nnels-drupal-modules-cals_importer#7]
From nnels created by [davekisly](https://github.com/davekisly) : BCLibCoop/nnels#135  

hi @gitschatz, just added (re-added?) the basic single node callback we discussed (verbally) to support the development and testing of marc exports of individual field collection items. You can go to an existing file resource, such as this one: https://dev.nnels.ca/field-collection/field-file-resource/477336 and you should now see a "Build Snippet" link. (We can call it whatever you think appropriate.)

Right now, this returns a var dump of the "stub array" attached to the node. We can chat about next steps here or by phone.

**Comment by gitschatz** [comment]
@davekisly Please find my snippet creation action [here](https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/file-snippet-build-revamp/cals_importer.exporter_file_snippets.inc#L45). Currently  it calls callables in the same file with scheme  _cals_importer_exporter_snippet_callback_{tag} to differentiate them from the other tag callbacks.

**Comment by gitschatz** [comment]
Should I be getting [these file snippet tags](https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/file-snippet-build-revamp/cals_importer.exporter_file_snippets.inc#L58) from another function somewhere like _cals_importer_get_tag_array ? That one seems broken in my branch (returns empty var), due to the MARC tag entities missing from my instance I believe.

**Comment by davekisly** [comment]
Good questions. Will get back to you this evening. Right now, it might be easiest to simply import the DEV database into your local (assuming you don't have many local configs you'd lose). But, yea, i'll have to figure out how to make the tags exportable (maybe a feature will do the trick here).

**Comment by gitschatz** [comment]
@davekisly Cheers.

I created a [feature for all the export dependencies on Dev](https://dev.nnels.ca/admin/structure/features/marcxml_export_components) and available in [nnels_public_features](https://github.com/BCLibCoop/nnels_public_features/tree/marcxml_exportl), however it only provides the entity type structure, Views, etc but not the tag and subfield entities (content) themselves.

**Comment by davekisly** [comment]
Hmm, i forget what method i used to import these between my local and dev, but we can probably use Deploy for this: https://www.drupal.org/project/deploy

**Comment by gitschatz** [comment]
It looks like you used a feeds importer on dev, but the current Entity type structure is a bit more complex than what was originally imported.

**Comment by davekisly** [comment]
Deploy might be useful beyond this immediate need, so i've added it to DEV and will see if i can make it work w/ our entities.

**Comment by davekisly** [comment]
Quick follow-up to say that Deploy may prove useful in terms of moving content between servers, but probably not for pulling the entities down to your local (unless your local is reachable as a target server by DEV). 

So, if u want to work w/ those entities on your local right now, the quickest approach would be to refresh your database (w/ that from DEV). 

I am, however, still thinking about extending feeds so we can quickly update our local environments - will review what's involved this week.

Alternatively, perhaps I can commit the array (now generated by the DB query) to code, in which case we wouldn't even need to export the entities over to PROD. We'd lose a little bit of future flexibility here (i.e., we'd have to make further updates in code, so it wouldn't be as accessible to @flittle8) but it would also be a bit more performant. I'll think further about this.

**Comment by gitschatz** [comment]
@davekisly Heads up: I've solved this with a Deploy plan with ViewsAggregator that export the entities into a feature (marc_tag_entities) here: https://github.com/BCLibCoop/nnels_public_features/commit/1a0df2c62d586edc915994589ea3778d819c7560

I will be recreating marcxml_export_components feature only for the non-entity supporting pieces to avoid the current conflicts.
